### ISSUE TITLE
hps to fpga brigdes are not enabled

### ISSUE THREAD

**Issue by bosrvd** [zangman/de10-nano#1]
Very good guide, my de10 nano board is booting up, but the hps2fpga brides are not enabled. So I can not interact between the arm core and the FPGA.

**Comment by duckyvirus** [comment]
went through this 3x, rebuilt the SDimage twice even.   quadruple checked the switches.  i get invalid FDT.   I went though the blink example again like a noob, and when i use the usb blaster it works perfectly.   but when attempting to use the bridge i get error -22.  the last time i went though it I even ensured I used the exact same versions for everything.  the only variable i cannot control is versions in buster.  please advise.

**Comment by duckyvirus** [comment]
UPDATE!    I found and figured out the issue.  in the WIKI it has base_fpga_region for the target path.   however it requires base-fpga-region.

**Comment by bosrvd** [comment]
The problem was that the overlay was sent to the wrong path
#echo -n "blink.dtbo" > blink/dtbo
must be:
#echo -n "blink.dtbo" > blink/path

**Comment by zangman** [comment]
@bosrvd Thanks for finding that, I've updated it in the wiki.

@duckyvirus Are you sure? I just tried it with the underscores and it worked for me.
