### ISSUE TITLE
Unable to fork and pull-request the wiki

### ISSUE THREAD

**Issue by kirkster96** [zangman/de10-nano#12]
Hello,

Is it possible to move all the wiki pages into a 'docs' directory so that I can suggest edits?

https://stackoverflow.com/a/11481887

There is great content on this repository and I would love to contribute. 😊

Thanks,

Cameron

**Comment by zangman** [comment]
Oh I had no idea that you couldn't do a pull request on github wiki. Thanks for raising this and I'd love for you to contribute. Let me go through the link you shared and see what's the best way to do this.

**Comment by zangman** [comment]
The link you shared is a pretty good idea. But I guess you'll need to first create a repository on your own account and then let me know to merge from your repo to mine. I'm happy to try it out if you want to give it a try.

**Comment by kirkster96** [comment]
Sounds good to me! Thank you for following up. I will work on creating a pull-request that contains changes that bring exactly what is in the wiki pages into the repo. 

I can follow-up with a second pull-request that contains my suggestions to improve the wiki pages.

**Comment by kirkster96** [comment]
I have attempted to submit the CLA and the form has given me an error message. I have attached a screenshot of the error to this comment. I attempted this from mobile & PC and from two different wifi connections.

Let me know if you have any recommendations to resolve this error.

![Capture](https://user-images.githubusercontent.com/15210279/168325254-ef3cf210-73ec-4cc8-8f3b-28d1670fef1f.PNG)

**Comment by zangman** [comment]
@kirkster96 Thank you so much for the amazing PR and for filling out the CONTRIBUTING.md file. It looks great. I'm now debating whether I should just scrap the wiki and keep everything in the `docs` folder. Might be easier for other to contribute and less overall work for me in copying it from there to the wiki. Thoughts?

**Comment by kirkster96** [comment]
No problem, I am happy to see that the PR was accepted!

I think that removing the wiki is the direction to go. Yesterday, I was following along with the [Building SoC Design](https://github.com/zangman/de10-nano/blob/master/docs/Building-SoC-Design.md) page and I found a link in the page content that points to the wiki page. So there are still more links that need to be updated with another PR. 

I will take some time to go through all the content carefully and make sure all the links are no longer pointing to the wiki. In the mean time, it may be a good idea to keep the wiki around in order to keep the links from breaking.

**Comment by zangman** [comment]
> Yesterday, I was following along with the [Building SoC Design](https://github.com/zangman/de10-nano/blob/master/docs/Building-SoC-Design.md) page and I found a link in the page content that points to the wiki page. So there are still more links that need to be updated with another PR.

Haha yea - I noticed that after I approved the PR as well. I fixed a couple of them, but there are quite a few. Thanks for taking the time to review and fix them, really appreciate your help.

Here's a quick grep of all the files and all the places where it needs to be updated:

#### Filelist:

```bash
~/de10-nano master > grep -l -R -o -P '.{30}https:\/\/.*?de10-nano\/wiki\/.{40}'                                                                                                           mango@tree task 1
docs/FPGA-SDRAM-Communication_-Avalon-MM-Host-Master-Component-Part-2.md
docs/Building-SoC-Design.md
docs/Creating-a-Bootscript.md
docs/Building-the-Kernel.md
docs/Simple-Hardware-Adder_-Setting-up-the-Adder.md
docs/Archlinux-ARM-Root-File-System.md
docs/Simple-Hardware-Adder_-Writing-the-Software.md
docs/FPGA-SDRAM-Communication_-Avalon-MM-Agent-Slave-Trigger-Component.md
docs/FPGA-SDRAM-Communication_-Avalon-MM-Host-Master-Component-Part-1.md
docs/Simple-Hardware-Adder_-Initial-Project-Setup.md
docs/FPGA-SDRAM-Communication_-More-about-the-Avalon-Memory-Mapped-Interface.md
docs/Flash-FPGA-On-Boot-Up.md
docs/FPGA-SDRAM-Communication_-Avalon-MM-Host-Master-Component-Part-3.md
docs/Debian-Root-File-System.md
docs/FPGA-SDRAM-Communication_-Introduction.md
docs/_Sidebar.md
docs/Building-the-SD-Card-image.md
```

#### Locations:

```bash

docs/FPGA-SDRAM-Communication_-Avalon-MM-Host-Master-Component-Part-2.md:` that we created over [here](https://github.com/zangman/de10-nano/wiki/Simple-Hardware-Adder:-Initial-Project-S
docs/FPGA-SDRAM-Communication_-Avalon-MM-Host-Master-Component-Part-2.md:steps as shown on [this page](https://github.com/zangman/de10-nano/wiki/Simple-Hardware-Adder:-Initial-Project-S
docs/FPGA-SDRAM-Communication_-Avalon-MM-Host-Master-Component-Part-2.md:plained in the [Simple Adder](https://github.com/zangman/de10-nano/wiki/Simple-Hardware-Adder:-Custom-Avalon-MM-
docs/FPGA-SDRAM-Communication_-Avalon-MM-Host-Master-Component-Part-2.md:he design as explained [here](https://github.com/zangman/de10-nano/wiki/Flash-FPGA-from-HPS-(running-Linux)) and
docs/Building-SoC-Design.md:` format as explained [here](<https://github.com/zangman/de10-nano/wiki/Flash-FPGA-from-HPS-(running-Linux)#crea
docs/Building-SoC-Design.md: the FPGA either on [boot-up](https://github.com/zangman/de10-nano/wiki/Flash-FPGA-On-Boot-Up) or from [the HPS]
docs/Building-SoC-Design.md:the [development environment](https://github.com/zangman/de10-nano/wiki/Setting-up-the-Development-Environment)
docs/Creating-a-Bootscript.md:bed in the [Building U-Boot](<https://github.com/zangman/de10-nano/wiki/Building-the-Universal-Bootloader-(U-Boo
docs/Creating-a-Bootscript.md:me>) section. [This section](<https://github.com/zangman/de10-nano/wiki/Building-the-Universal-Bootloader-(U-Boo
docs/Building-the-Kernel.md: for WIFI as explained [here](https://github.com/zangman/de10-nano/wiki/%5BOptional%5D-Setting-up-Wifi#compile-t
docs/Simple-Hardware-Adder_-Setting-up-the-Adder.md:. This is covered over [here](https://github.com/zangman/de10-nano/wiki/Configuring-the-Device-Tree) so I won't
docs/Simple-Hardware-Adder_-Setting-up-the-Adder.md:gh the steps described [here](https://github.com/zangman/de10-nano/wiki/Configuring-the-Device-Tree) and verify
docs/Simple-Hardware-Adder_-Setting-up-the-Adder.md: already been covered [here](<https://github.com/zangman/de10-nano/wiki/Flash-FPGA-from-HPS-(running-Linux)>) an
docs/Archlinux-ARM-Root-File-System.md:h all the steps listed [here](https://github.com/zangman/de10-nano/wiki/Building-the-SD-Card-image) all the way
docs/Archlinux-ARM-Root-File-System.md: the [kernel and device tree](https://github.com/zangman/de10-nano/wiki/Building-the-SD-Card-image#kernel-and-de
docs/Archlinux-ARM-Root-File-System.md:d back over to [this section](https://github.com/zangman/de10-nano/wiki/Building-the-SD-Card-image#cleanup) to c
docs/Simple-Hardware-Adder_-Writing-the-Software.md:up the path in [this section](https://github.com/zangman/de10-nano/wiki/Setting-up-the-Development-Environment#a
docs/Simple-Hardware-Adder_-Writing-the-Software.md: to `ON` as described [here](<https://github.com/zangman/de10-nano/wiki/Flash-FPGA-from-HPS-(running-Linux)#set-
docs/FPGA-SDRAM-Communication_-Avalon-MM-Agent-Slave-Trigger-Component.md:plained in the [Simple Adder](https://github.com/zangman/de10-nano/wiki/Simple-Hardware-Adder:-Custom-Avalon-MM-
docs/FPGA-SDRAM-Communication_-Avalon-MM-Host-Master-Component-Part-1.md:MM Read and Write interfaces](https://github.com/zangman/de10-nano/wiki/FPGA-SDRAM-Communication:-More-about-the
docs/Simple-Hardware-Adder_-Initial-Project-Setup.md:HRD to the working directory](https://github.com/zangman/de10-nano/wiki/Building-SoC-Design#copy-the-ghrd-to-wor
docs/FPGA-SDRAM-Communication_-More-about-the-Avalon-Memory-Mapped-Interface.md: to the [Primer on Avalon MM](https://github.com/zangman/de10-nano/wiki/Simple-Hardware-Adder:-Primer-on-Avalon-
docs/FPGA-SDRAM-Communication_-More-about-the-Avalon-Memory-Mapped-Interface.md:n the [Simple Hardware Adder](https://github.com/zangman/de10-nano/wiki/Simple-Hardware-Adder:-Custom-Avalon-MM-
docs/FPGA-SDRAM-Communication_-More-about-the-Avalon-Memory-Mapped-Interface.md:ed from this [9 minute video](https://www.youtube.com/watch?v=8GAqT3nzHeQ). I strongly recommend watching this one, it was a lightbulb moment for me. Below, I will try and expand a bit more over what the video covers. But if everything in the video makes sense to you, feel free to just skip to the [last section](https://github.com/zangman/de10-nano/wiki/FPGA-SDRAM-Communication:-More-about-the
docs/Flash-FPGA-On-Boot-Up.md:he U-Boot to flash the FPGA](<https://github.com/zangman/de10-nano/wiki/Building-the-Universal-Bootloader-(U-Boo
docs/FPGA-SDRAM-Communication_-Avalon-MM-Host-Master-Component-Part-3.md: designs [without rebooting](<https://github.com/zangman/de10-nano/wiki/Flash-FPGA-from-HPS-(running-Linux)>) ev
docs/FPGA-SDRAM-Communication_-Avalon-MM-Host-Master-Component-Part-3.md:you can [create a bootscript](https://github.com/zangman/de10-nano/wiki/Creating-a-Bootscript) which will make i
docs/Debian-Root-File-System.md:ng up WIFI as detailed [here](https://github.com/zangman/de10-nano/wiki/%5BOptional%5D-Setting-up-Wifi#install-t
docs/FPGA-SDRAM-Communication_-Introduction.md:n the [Simple Hardware Adder](https://github.com/zangman/de10-nano/wiki/Simple-Hardware-Adder:-Introduction) pro
docs/_Sidebar.md:niversal Bootloader (U-Boot)](https://github.com/zangman/de10-nano/wiki/Building-the-Universal-Bootloader-(U-Boo
docs/_Sidebar.md:[Custom Avalon MM Components](https://github.com/zangman/de10-nano/wiki/Simple-Hardware-Adder:-Custom-Avalon-MM-
docs/_Sidebar.md:nt/Slave - Trigger Component](https://github.com/zangman/de10-nano/wiki/FPGA-SDRAM-Communication:-Avalon-MM-Agen
docs/_Sidebar.md:* [Avalon MM Host/Master - 1](https://github.com/zangman/de10-nano/wiki/FPGA-SDRAM-Communication:-Avalon-MM-Host
docs/_Sidebar.md:* [Avalon MM Host/Master - 2](https://github.com/zangman/de10-nano/wiki/FPGA-SDRAM-Communication:-Avalon-MM-Host
docs/_Sidebar.md:* [Avalon MM Host/Master - 3](https://github.com/zangman/de10-nano/wiki/FPGA-SDRAM-Communication:-Avalon-MM-Host
docs/Building-the-SD-Card-image.md:, then jump to [this section](https://github.com/zangman/de10-nano/wiki/Archlinux-ARM-Root-File-System) to conti
```

**Comment by Andy2No** [comment]
Having just taken the easy route and flashed a ready made image, I have a suggestion to add to the part of the readme that relates to doing that, mostly just linking to the part of the relevant page that explains what to do with the image:

ON PAGE:

README.md
https://github.com/zangman/de10-nano#readme

UNDER:
https://github.com/zangman/de10-nano#can-i-just-get-the-image-i-dont-want-to-go-through-the-guide-to-get-debian-on-my-de10-nano

**Can I just get the image? I don't want to go through the guide to get Debian on my DE10-Nano.**
-> Sure, You can download the SD Card image from the releases page.

ADD:

>See **Creating the SD Card Image**

( link this to "Writing to SD Card" on de10-nano/docs/Building-the-SD-Card-image.md https://github.com/zangman/de10-nano/blob/master/docs/Building-the-SD-Card-image.md#writing-to-sd-card )


ON PAGE:

Building-the-SD-Card-image.md


UNDER:

**"Writing in Windows"**
https://github.com/zangman/de10-nano/blob/master/docs/Building-the-SD-Card-image.md#writing-in-windows

ADD:
>Rufus can also write from a zipped image file, without needing to unzip it.

**Comment by zangman** [comment]
@Andy2No Thanks for sharing - would you be okay to send a PR with these changes? I can review and accept it. You'll need to complete the steps in [CONTRIBUTING.md](https://github.com/zangman/de10-nano/blob/master/CONTRIBUTING.md) file first though.

**Comment by Andy2No** [comment]
At first reading, I'm not happy with the terms of google's CLA.

I am happy for all or any part of any suggestion I make to be used by someone else though, whether or not it's with the same exact wording.  I'm happy for copyright to pass to whoever chooses to implement my suggestions, especially since they are just suggestions.

**Comment by kirkster96** [comment]
@zangman sorry it took so long. I became very busy with work. I hope that these changes complete this issue.

Let me know if you see something that needs to be corrected and I can go through it again.

**Comment by zangman** [comment]
@kirkster96 Amazing, thank you so much! Really appreciate your effort in cleaning up and making this wiki more user friendly.

**Comment by Andy2No** [comment]
@kirkster96 In trying to read through it all, I'm still getting a little lost because there isn't a consistent link at the bottom of each page to take me to a next one.

I think it would help if the whole thing was linked as a book, so that after reading one page you can go straight to the next one - or a next one.  At present, the last page of each sub section just has a back link, to the previous page in that sub section.

Also, at the bottom of the main readme page, it would be good if it had a link to either the table of contents, or the first linked page in that table - or maybe both, but people who've used github before are probably quite comfortable with clicking the Code tab to get back to the readme, so I'd suggest the "Next" link at the bottom of the readme should link to the "Getting Started" page.

**Comment by kirkster96** [comment]
> @kirkster96 In trying to read through it all, I'm still getting a little lost because there isn't a consistent link at the bottom of each page to take me to a next one.
> 
> I think it would help if the whole thing was linked as a book, so that after reading one page you can go straight to the next one - or a next one. At present, the last page of each sub section just has a back link, to the previous page in that sub section.
> 
> Also, at the bottom of the main readme page, it would be good if it had a link to either the table of contents, or the first linked page in that table - or maybe both, but people who've used github before are probably quite comfortable with clicking the Code tab to get back to the readme, so I'd suggest the "Next" link at the bottom of the readme should link to the "Getting Started" page.


Thank you, I will create a new issue and work on creating the nagivation links. I will make a new PR for that when I am done. I think this issue can be closed now that the PR has been accepted.

**Comment by zangman** [comment]
@Andy2No I had some time today - so I updated the nav links to link to the next and previous section as you suggested. I don't think Next needs to go to the README as there is a link to the TOC on every page.

@kirkster96 FYI
