### ISSUE TITLE
Failed serial console login under Release Debian for DE-10 Nano

### ISSUE THREAD

**Issue by ryan296** [zangman/de10-nano#2]
Hi

I have downloaded the image file that you released it. But when I try to login by using serial console, I can't figure which is the root password. Neither blank space, root or passwd works, so I'm pretty confused. Maybe it seems like a silly question, but could you help me to figure out the login and password for it?

**Comment by hellgate202** [comment]
Your root password is created during RootFS creation, simply type passwd during this and enter your root password

**Comment by zangman** [comment]
Sorry about that - I completely missed this. I think the password is "hey". Can you try that? I'll try and remove it from subsequent images.

**Comment by zangman** [comment]
Just a note - if I remove the password for root, it doesn't allow me to login at all. Probably doing something silly, but for the new release and all subsequent ones, I'll just have "root" as the password.
