### ISSUE TITLE
Transparent diagrams in github's dark mode are hard to read

### ISSUE THREAD

**Issue by amstan** [zangman/de10-nano#8]
Perhaps consider adding a background (even if it's just white) or a white glow/shadow around the black-on-transparent lines.

Example of an affected page: https://github.com/zangman/de10-nano/wiki/FPGA-SDRAM-Communication:-Avalon-MM-Host-Master-Component-Part-1

![image](https://user-images.githubusercontent.com/160217/149245082-6945e79e-d016-4696-a874-d6d635f0ed75.png)

**Comment by zangman** [comment]
Ah, thanks for letting me know! I'll add a background for it. For now a workaround is to open the image in a new tab by right clicking on it, that should allow it to render correctly.

**Comment by zangman** [comment]
Updated the image with a white background.
